id: A3BB33B39
title: Guru Yoga
type: translation
pechas:
- IDFC2CA34
- I55111993
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:54:54.714331
  last_modified_at: 2023-01-04 11:54:54.714342
  collections:
  - Fourth Dodrupchen Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  IDFC2CA34/76E5: 8B9C
  I55111993/4EAA: 8B9C
